---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен быть доступен на различных устройствах
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы 
implicit:
  - При добавлении товара в корзину должна быть возможность выбрать количество товара
  - Пользователь должен иметь возможность просматривать свои оформленные заказы
  - Цены на товары должны указываться в местной валюте
  - Пользователь должен пройти регистрацию, чтобы оформить заказ
  - При удалении товара из корзины должно появляться окно подтверждения
  - На первой странице с товарами не должно быть кнопки "предыдущая страница"
